---
- hosts: kodi
  remote_user: lincoln
  become: yes
  tasks:
  - name: Instalar properties
    apt:
     name: software-properties-common
     update_cache: yes
     state: latest
  - name: adicionar repositorio
    apt_repository:
     repo: ppa:team-xbmc/ppa
     update_cache: yes 
  - name: Instalar Kodi
    apt:
     name: kodi
     update_cache: yes
     state: latest
